### ISSUE TITLE
Is this usable?

### ISSUE THREAD

**Issue by malte-v** [casbin/casbin-rs#25]
In the main repo, it says this project is "work in progress" and the crate is also not published. Does this mean it isn't usable at this point in time? If so, can you give an ETA on how long it will take? It looks like there hasn't been much activity in here lately... Thanks!

**Comment by andrewbanchich** [comment]
I'm also wondering this @xcaptain

**Comment by xcaptain** [comment]
@andrewbanchich @malte-v This project is still under development, I don't use it in my daily work anymore so recent development is slow. It's ok to use it in a single-threaded scene, but not in the multi-threaded scene because we heavily use `Rc` and `RefCell`, these pointers are not shareable between threads.

Anyway, contributions are welcomed, I think with only a small amount of work, this project can get production-ready.

**Comment by xcaptain** [comment]
@andrewbanchich I added multi-thread support for casbin at https://github.com/casbin/casbin-rs/pull/26 and I added a simple demo at https://github.com/xcaptain/voyager.rs/blob/master/examples/json.rs casbin now works in a multi thread/future based web server.

@GopherJ has an attempt to add diesel adapter for casbin at https://github.com/casbin/casbin-rs/pull/18 but didn't get merged, do you have interest to help continue this pull request if you need to use casbin and database at your work?

**Comment by xcaptain** [comment]
A 0.1.0 version has just been released at https://crates.io/crates/casbin hope more rust people can use this library to do authorization
