### ISSUE TITLE
Consider using the subslice patterns

### ISSUE THREAD

**Issue by xcaptain** [casbin/casbin-rs#67]
Rust 1.42 will provide some pattern matching improvements and will be released on Mar 12, for details see https://blog.rust-lang.org/inside-rust/2020/03/04/recent-future-pattern-matching-improvements.html

I think it's a good opportunity to replace the current `Vec<&str>` apis to `[&str; 4]` and pattern matching whether the passing argument is of length 3 or 4

**Comment by VanillaBrooks** [comment]
Hey, I would potentially like to take this one. Although, some preliminary grepping shows over 150 mentions of Vec<&str>, probably 80+ of which are function argument types. Could you point me in the direction of some examples in the current code ?

> whether the passing argument is of length 3 or 4

what does "passing argument" mean in this context ? Are you suggesting to parse whether the last argument is an empty `str` ? As in parsing :
["foo", "bar", "baz", "" ]  vs [ "foo", "bar", "baz", "optional"] ?

**Comment by xcaptain** [comment]
@VanillaBrooks Thanks for the help, I would suggest you start from `enforce` method, normally `enforce` takes 3 parameters those are sub, obj and act, which means check if one subject can act on one object. But in some situations a subject may belong 2 domains(organizations), so we must provide one more domain parameter.

You can see the example at 

https://github.com/casbin/casbin-rs/blob/67e85000c7420a71598fb5bb92dc2838d1ec682c/src/model/default_model.rs#L487-L491

You can try turn it into

```rust
e.enforce("alice", "domain1", "data1", "read")
```

**Comment by xcaptain** [comment]
@VanillaBrooks After some considerations, I think this is not an issue, the current behavior is fine, what do you think

**Comment by VanillaBrooks** [comment]
Well I'm unsure how the ergonomics would work, but I think they would be less than that of the current `Vec<&str>` depending on how things are done. I suppose one solution would be to make all methods that accept `Vec<&str>` to move to something like this:

```
fn enforce_vec(params: Vec<&str>, other_args: ()) -> () {}
fn encorce_array<'a, T: Into<[&'a str; 4]>>(stuff: T, other_args: ()) -> () {}

impl From<[&str; 3]> for [&str; 4] {
    fn from(e: [&str; 3]) -> [&str; 4] {}
}
```
However, due to the orphan rule `From` cant be implemented for `[&str;4]`, so wrapper types would need to be added. I think this would make things more confusing for little benefit. I believe it would also be slower than `Vec<&str>` on average due to extra allocations in `from`.
 
Alternatively we could do something like this:

```
trait EnforceHelper {
    fn enforce_help(&self);
}

impl EnforceHelper for [&str; 3] {
    fn enforce_help(&self) -> () {}
}
impl EnforceHelper for [&str; 4] {
    fn enforce_help(&self) -> () {}
}
```

and then make the `Vec<&str>` to `enforce` `T:EnforceHelper`, but this skips the entire subslice patters that we were originally talking about;  

Overall there would be a lot of work for mostly minimal gains. I think that It would be good to keep the `Vec<&str>` api.

**Comment by xcaptain** [comment]
@VanillaBrooks  A detailed discussion about `Vec<&str>` can be found at https://github.com/casbin/casbin-rs/pull/75

Change `Vec<&str>` to `[&str, 3]` doesn't provide any benefits for this project, I will close this issue.
