### ISSUE TITLE
Add Casbin-RS to our feature set table

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-rs#71]
See: https://casbin.org/docs/en/overview#feature-set-for-different-languages

![image](https://user-images.githubusercontent.com/3787410/76877733-d11a9580-68ae-11ea-818f-20ff8ef6d473.png)

**Comment by hsluoyz** [comment]
@GopherJ @xcaptain @PsiACE

**Comment by GopherJ** [comment]
@hsluoyz  I would say we have all except `ABAC` and `FilteredAdapter`, about `ABAC` @xcaptain  may know more than me, I have never used it so I have no idea.

**Comment by xcaptain** [comment]
@GopherJ casbin-rs doesn't support ABAC yet, because we are using `Vec<&str>` as `enforce` parameter, which requires all elements in the vector have the same type, while `ABAC` requires matching on some attributes of an object.

Do you want to make a pull request to the doc site about the current status of casbin-rs?

**Comment by hsluoyz** [comment]
Thanks @GopherJ @xcaptain ! Can anyone update the docs?

**Comment by xcaptain** [comment]
I think the `FilteredAdapter` would be much easier to implement, do we need to implement it first?

**Comment by xcaptain** [comment]
@hsluoyz https://github.com/casbin/casbin-website/pull/60 please review

**Comment by hsluoyz** [comment]
Merged.
